POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Pentti Hirvonen",
    "number": "044-1212121"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Pekka Karvonen",
    "number": ""
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "",
    "number": "050-1234567"
}

###

POST https://bold-mountain-1477.fly.dev/api/persons/
content-type: application/json

{
    "name": "Pentti Hirvonen",
    "number": "044-1212121"
}

###

POST https://bold-mountain-1477.fly.dev/api/persons/
Content-Type: application/json

{
    "name": "Pekka Karvonen",
    "number": ""
}

###

POST https://bold-mountain-1477.fly.dev/api/persons/
Content-Type: application/json

{
    "name": "",
    "number": "050-1234567"
}